In [2]:
import numpy as np 
STUDENT_NAME = "Kristine Cassandra T. Cacapit" 
STUDENT_ID = 25962 
 
np.random.seed(STUDENT_ID) 
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10) 
print(f"{STUDENT_NAME}'s Array:", data) 
 
mean_val = np.mean(data) 
std_val = np.std(data) 
print("Mean:", mean_val, "Std Dev:", std_val) 

Kristine Cassandra T. Cacapit's Array: [58 83 63  7 38 26 18  7 39 82]
Mean: 42.1 Std Dev: 26.990553903171385


In [3]:
import numpy as np 
STUDENT_NAME = "Kristine Cassandra T. Cacapit" 
STUDENT_ID = 25962 
 
np.random.seed(STUDENT_ID) 
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4)) 
print(f"{STUDENT_NAME}'s Matrix:\n", matrix) 
 
row_sums = np.sum(matrix, axis=1) 
col_sums = np.sum(matrix, axis=0) 
print("Row sums:", row_sums) 
print("Column sums:", col_sums) 

Kristine Cassandra T. Cacapit's Matrix:
 [[26 19 31 21]
 [ 7  6 26 18]
 [18  7  7 30]]
Row sums: [97 57 62]
Column sums: [51 32 64 69]


In [4]:
import numpy as np 
STUDENT_NAME = "Kristine Cassandra T. Cacapit" 
STUDENT_ID = 25962 
 
np.random.seed(STUDENT_ID) 
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3)) 
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d) 
 
slice_mid = arr3d[:,1,:] 
print("Slice[:,1,:]:\n", slice_mid) 

Kristine Cassandra T. Cacapit's 3D Array:
 [[[ 9  2  4]
  [ 6  5  9]
  [ 1  1  6]]

 [[ 6  1  6]
  [10  7  3]
  [ 1 11  0]]

 [[ 9 11  2]
  [ 5  2 11]
  [11 10  2]]]
Slice[:,1,:]:
 [[ 6  5  9]
 [10  7  3]
 [ 5  2 11]]


In [5]:
STUDENT_NAME = "Kristine Cassandra T. Cacapit" 
STUDENT_ID = 25962
 
np.random.seed(STUDENT_ID) 
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10) 
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)] 
print(f"{STUDENT_NAME}'s Original:", x) 
print("Filtered subset:", filtered) 

Kristine Cassandra T. Cacapit's Original: [58 83 63  7 38 26 18  7 39 82]
Filtered subset: [58 38 26 18 39]


In [6]:
import numpy as np 
STUDENT_NAME = "Kristine Cassandra T. Cacapit" 
STUDENT_ID = 25962
 
np.random.seed(STUDENT_ID) 
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2)) 
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2)) 
print("Matrix A:\n", A) 
print("Matrix B:\n", B) 
 
product = A @ B 
det_A = np.linalg.det(A) 
print("A @ B:\n", product) 
print("Determinant of A:", det_A)

Matrix A:
 [[26 19]
 [31 21]]
Matrix B:
 [[ 7  6]
 [26 18]]
A @ B:
 [[676 498]
 [763 564]]
Determinant of A: -43.00000000000009


In [7]:
import numpy as np 
STUDENT_NAME = "Kristine Cassandra T. Cacapit" 
STUDENT_ID = 25962
 
angles = np.linspace(0, 2*np.pi, 8) 
sine_vals = np.sin(angles) 
cos_vals = np.cos(angles) 
print(f"{STUDENT_NAME}'s Angles:", angles) 
print("Sine:", sine_vals) 
print("Cosine:", cos_vals) 

Kristine Cassandra T. Cacapit's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [8]:
import numpy as np 
STUDENT_NAME = "Kristine Cassandra T. Cacapit" 
STUDENT_ID = 25962

arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4)) 
arr[::2, ::2] = 0 
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr) 

Kristine Cassandra T. Cacapit's Modified 4x4 Array:
 [[ 0  7  0 30]
 [29 18 23 11]
 [ 0  4  0 12]
 [ 1 26 28 16]]


In [9]:
import numpy as np 
STUDENT_NAME = "Kristine Cassandra T. Cacapit" 
STUDENT_ID = 25962

np.random.seed(STUDENT_ID) 
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10) 
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail') 
print(f"{STUDENT_NAME}'s Scores:", scores) 
print("Grades:", grades)

Kristine Cassandra T. Cacapit's Scores: [57 82 62  6 37 25 17  6 38 81]
Grades: ['Fail' 'Pass' 'Pass' 'Fail' 'Fail' 'Fail' 'Fail' 'Fail' 'Fail' 'Pass']


In [10]:
import numpy as np 
STUDENT_NAME = "Kristine Cassandra T. Cacapit" 
STUDENT_ID = 25962

np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4)) 
flat_arr = arr.flatten() 
transposed_arr = arr.T 
print("Original array:\n", arr) 
print("Flattened:", flat_arr) 
print("Transposed:\n", transposed_arr) 

Original array:
 [[26 19 31 21]
 [ 7  6 26 18]
 [18  7  7 30]]
Flattened: [26 19 31 21  7  6 26 18 18  7  7 30]
Transposed:
 [[26  7 18]
 [19  6  7]
 [31 26  7]
 [21 18 30]]


In [11]:
import numpy as np 
STUDENT_NAME = "Kristine Cassandra T. Cacapit" 
STUDENT_ID = 25962

np.random.seed(STUDENT_ID) 
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3)) 
mask = arr % 2 == 0 
arr[mask] = -1 
print("Array with conditional replacements:\n", arr) 

Array with conditional replacements:
 [[-1 19 31]
 [21  7 -1]
 [-1 -1 -1]]


In [15]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Kristine Cassandra T. Cacapit"
STUDENT_ID = 25962

np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'Name': [STUDENT_NAME]*5, 
    'Score': np.random.randint(STUDENT_ID%50, 
STUDENT_ID%100+50,5), 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5) 
    }) 
print(df) 

                            Name  Score  YearsCodePro
0  Kristine Cassandra T. Cacapit     69             9
1  Kristine Cassandra T. Cacapit     94             1
2  Kristine Cassandra T. Cacapit     74             1
3  Kristine Cassandra T. Cacapit     18             6
4  Kristine Cassandra T. Cacapit     49             6


In [16]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Kristine Cassandra T. Cacapit"
STUDENT_ID = 25962

df = pd.DataFrame({ 
    'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'], 
    # Corrected to use a functional salary range, e.g., 40000 to 150000 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean() 
print(avg_salary)


EdLevel
Bachelor    102217.5
Master       84579.0
PhD          44561.0
Name: ConvertedComp, dtype: float64


In [17]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Kristine Cassandra T. Cacapit"
STUDENT_ID = 25962

np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'Country': ['Philippines','USA','UK','Canada','Germany'], 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
top5 = df.sort_values(by='ConvertedComp', ascending=False) 
print(top5) 


       Country  ConvertedComp
1          USA         140798
3       Canada         136390
4      Germany         108005
2           UK          82612
0  Philippines          75769


In [18]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Kristine Cassandra T. Cacapit"
STUDENT_ID = 25962


np.random.seed(STUDENT_ID) 
df = pd.DataFrame({ 
    'Name':[STUDENT_NAME]*5, 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5) 
}) 
high_exp = df[df['YearsCodePro']>STUDENT_ID%10] 
print(high_exp) 

                            Name  YearsCodePro
0  Kristine Cassandra T. Cacapit             9
2  Kristine Cassandra T. Cacapit             4
3  Kristine Cassandra T. Cacapit             6
4  Kristine Cassandra T. Cacapit             5


In [19]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Kristine Cassandra T. Cacapit"
STUDENT_ID = 25962

 
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 
150000, 5)}) 
 
bins = [0, 50000, 100000, 150000, 200000] 
labels = ['0-50k', '50-100k', '100-150k', '>150k'] 
 
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels) 
print(df) 


   ConvertedComp   Bracket
0          72273   50-100k
1          82353   50-100k
2         100710  100-150k
3         141629  100-150k
4          96956   50-100k


In [20]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Kristine Cassandra T. Cacapit"
STUDENT_ID = 25962

np.random.seed(STUDENT_ID) 
 
# Original Code Issue:  
# np.random.randint(STUDENT_ID%40000, STUDENT_ID%150000, 5)  
# -> np.random.randint(12345, 12345, 5) which is a zero-length range. 
 
# Corrected Code: Using a functional salary range (40000 to 150000) 
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 
150000, 5)}) 
 
df['LogComp'] = np.log(df['ConvertedComp']) 
print(df) 

   ConvertedComp    LogComp
0          75769  11.235445
1         140798  11.855082
2          82612  11.321910
3         136390  11.823274
4         108005  11.589933


In [21]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Kristine Cassandra T. Cacapit"
STUDENT_ID = 25962


np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5), 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
corr_matrix = df.corr() 
print(corr_matrix) 


               YearsCodePro  ConvertedComp
YearsCodePro       1.000000      -0.057636
ConvertedComp     -0.057636       1.000000


In [24]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Kristine Cassandra T. Cacapit"
STUDENT_ID = 25962

np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'], 
    'ConvertedComp': np.random.randint(40000, 150000, 5)  
}) 
 
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index() 
print(summary) 

    EdLevel      mean    median           std
0  Bachelor  106079.5  106079.5  42865.520182
1    Master  124401.5  124401.5  23188.152675
2       PhD   82612.0   82612.0           NaN


In [25]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Kristine Cassandra T. Cacapit"
STUDENT_ID = 25962

np.random.seed(STUDENT_ID) 
 
# Generate salaries: [100727, 136195, 130612, 100727, 95233] 
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 
150000, 5)}) 
 
threshold = 110000 
 
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No') 
 
print(df) 

   ConvertedComp HighPay
0          75769      No
1         140798     Yes
2          82612      No
3         136390     Yes
4         108005      No


In [27]:
import numpy as np 
import pandas as pd 
STUDENT_NAME = "Kristine Cassandra T. Cacapit"
STUDENT_ID = 25962

np.random.seed(STUDENT_ID) 
 
df = pd.DataFrame({ 
    'Country': ['Philippines','USA','UK','Canada','Germany'], 
    'ConvertedComp': np.random.randint(40000, 150000, 5) 
}) 
 
# Group by 'Country' and calculate the mean and max 'ConvertedComp' 
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max']) 
print(top_countries) 

                 mean     max
Country                      
Canada       136390.0  136390
Germany      108005.0  108005
Philippines   75769.0   75769
UK            82612.0   82612
USA          140798.0  140798
