In [3]:
import numpy as np

years_exp = np.array([1, 3, 5, 7, 10]) 
print("Years of Experience:", years_exp)

salaries = np.array([[50, 60, 70], [80, 90, 100]]) 
print("Salary Matrix:\n", salaries)

zeros_array = np.zeros((2, 2))  
ones_array = np.ones((2, 3))	
print("Zeros Array:\n", zeros_array) 
print("Ones Array:\n", ones_array)


Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
exp_plus_5 = years_exp + 5 
print("Years + 5:", exp_plus_5)

exp_times_2 = years_exp * 2 
print("Years * 2:", exp_times_2)

sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6]) 
dot_result = np.dot(sample1, sample2) 
print("Dot Product:", dot_result)



Years + 5: [ 6  8 10 12 15]
Years * 2: [ 2  6 10 14 20]
Dot Product: 32


In [5]:
print("First year of experience:", years_exp[0])

print("First two salaries:", salaries[0, :2]) 

print("Second column salaries:", salaries[:, 1])

print("Last year of experience:", years_exp[-1])



First year of experience: 1
First two salaries: [50 60]
Second column salaries: [60 90]
Last year of experience: 10


In [8]:
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3)) 
print("Reshaped Experience Array:\n", reshaped_exp)

flattened_exp = reshaped_exp.flatten() 
print("Flattened Array:", flattened_exp)

print("Transposed Array:\n", reshaped_exp.T)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [9]:
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus 
print("Salaries after bonus:\n", salaries_with_bonus)


Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]]


In [10]:
print("Mean experience:", np.mean(years_exp))

print("Std deviation of experience:", np.std(years_exp))

print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries))

print("Sum of all salaries:", np.sum(salaries))


Mean experience: 5.2
Std deviation of experience: 3.1240998703626617
Max salary: 100 Min salary: 50
Sum of all salaries: 450


In [11]:
angles = np.array([0, np.pi/4, np.pi/2]) 
print("Sine of angles:", np.sin(angles)) 
print("Cosine of angles:", np.cos(angles))

salary_sums = np.apply_along_axis(np.sum, 1, salaries) 
print("Sum of Salaries per person:", salary_sums)


Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270]


In [15]:
import pandas as pd

data = np.random.randint(1, 50, size=(5, 3))

df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z']) 
print("Generated Data:\n", df_data)

df_data['Log_X'] = np.log(df_data['X']) 
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)

print("Correlation Matrix:\n", df_data.corr())


Generated Data:
     X   Y   Z
0  22   4  21
1  37  12   1
2   3  45   9
3   3   4  39
4  25   2  49
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  22   4  21  3.091042  2.000000
1  37  12   1  3.610918  3.464102
2   3  45   9  1.098612  6.708204
3   3   4  39  1.098612  2.000000
4  25   2  49  3.218876  1.414214
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000 -0.445754 -0.230520  0.973156 -0.369336
Y      -0.445754  1.000000 -0.578244 -0.524171  0.988835
Z      -0.230520 -0.578244  1.000000 -0.095858 -0.683746
Log_X   0.973156 -0.524171 -0.095858  1.000000 -0.472510
Sqrt_Y -0.369336  0.988835 -0.683746 -0.472510  1.000000


In [16]:
import pandas as pd

df_data.to_csv('sample_data.csv', index=False) 
print("Data saved to 'sample_data.csv'.")

df_imported = pd.read_csv('sample_data.csv') 
print("Imported DataFrame:\n", df_imported)

summary_stats = df_imported.describe() 
print("Summary Statistics:\n", summary_stats)

print("Column Means:\n", df_imported.mean()) 
print("Column Standard Deviations:\n", df_imported.std())


Data saved to 'sample_data.csv'.
Imported DataFrame:
     X   Y   Z     Log_X    Sqrt_Y
0  22   4  21  3.091042  2.000000
1  37  12   1  3.610918  3.464102
2   3  45   9  1.098612  6.708204
3   3   4  39  1.098612  2.000000
4  25   2  49  3.218876  1.414214
Summary Statistics:
                X         Y          Z     Log_X    Sqrt_Y
count   5.000000   5.00000   5.000000  5.000000  5.000000
mean   18.000000  13.40000  23.800000  2.423612  3.117304
std    14.798649  18.07761  20.079841  1.224628  2.145465
min     3.000000   2.00000   1.000000  1.098612  1.414214
25%     3.000000   4.00000   9.000000  1.098612  2.000000
50%    22.000000   4.00000  21.000000  3.091042  2.000000
75%    25.000000  12.00000  39.000000  3.218876  3.464102
max    37.000000  45.00000  49.000000  3.610918  6.708204
Column Means:
 X         18.000000
Y         13.400000
Z         23.800000
Log_X      2.423612
Sqrt_Y     3.117304
dtype: float64
Column Standard Deviations:
 X         14.798649
Y         18.077610


In [36]:
import pandas as pd
import numpy as np

df_kaggle = pd.read_csv(r"C:\Users\KC\stack-overflow-developer-survey-2024\survey_results_public.csv")
print("Loaded Dataset:\n", df_kaggle.head())

df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']] 
print("Subset of Data:\n", df_subset.head())

df_clean = df_subset.dropna() 
print("Cleaned Data:\n", df_clean.head())

df_clean['YearsCodePro'] = pd.to_numeric(df_clean['YearsCodePro'], errors='coerce')

df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')

grouped_data = df_clean.groupby(['Country', 'ExperienceLevel'])['ConvertedCompYearly'].mean()
print("Grouped Average Salary:\n", grouped_data.head())

grouped_data = grouped_data.reset_index() 
print("Formatted Grouped Data:\n", grouped_data.head())


Loaded Dataset:
    ResponseId                      MainBranch                 Age  \
0           1  I am a developer by profession  Under 18 years old   
1           2  I am a developer by profession     35-44 years old   
2           3  I am a developer by profession     45-54 years old   
3           4           I am learning to code     18-24 years old   
4           5  I am a developer by profession     18-24 years old   

            Employment RemoteWork   Check  \
0  Employed, full-time     Remote  Apples   
1  Employed, full-time     Remote  Apples   
2  Employed, full-time     Remote  Apples   
3   Student, full-time        NaN  Apples   
4   Student, full-time        NaN  Apples   

                                    CodingActivities  \
0                                              Hobby   
1  Hobby;Contribute to open-source projects;Other...   
2  Hobby;Contribute to open-source projects;Other...   
3                                                NaN   
4                